name: L10n
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  mockery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache: true
          go-version: 'stable'
      - name: Install xgotext
        run: |
          go install github.com/leonelquinteros/gotext/cli/xgotext@latest
      - name: Generate pot files
        run: |
          ~/go/bin/xgotext -default web -pkg-tree ./cmd/web -out ./pkg/embed/locales
          ~/go/bin/xgotext -default cli -pkg-tree ./cmd/cli -out ./pkg/embed/locales
      - uses: stefanzweifel/git-auto-commit-action@v5
        name: Commit changes
        with:
          commit_message: "chore(l10n): update pot files"
